---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  labels:
    app: diplom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diplom-app
  template:
    metadata:
      labels:
        app: diplom-app
    spec:
      containers:
      - name: diplom-app
        image: cr.yandex/<REGISTRY_ID>/diplom-app:1.0
        ports:
        - containerPort: 80
