---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diplom-app-ingress
spec:
  rules:
    - host: diplom-app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: diplom-app-service
                port:
                  number: 80
